kaltura/playkit-js-transcript

src/components/Caption/caption.scss

If set css property user-select with "text" value user can select the caption line without changes for paddings;

chore(FEV-449): made caption line selectable

---

src/transcript-plugin.tsx

- prevent reloading of captions when user select "off" option;
- fix issue when caption language haven't defined (local storage doesn't have information about caption lang) and configuration contains "auto" as a default captions.

chore(FEV-458): prevent reloading of captions when user select "off" option

---

src/utils.ts

change a regex for parsing dfxp files
supported captions time formats:
xx:xx:xx,xxx
xx:xx:xx,xx
xx:xx:xx,x
xx:xx:xx

chore(REACH2-756): fix a parser for dfxp files

---

src/components/Transcript/transcript.tsx

- keep latest highlighted caption as an active until next caption become highlighted (got an active status)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/29)

chore(REACH2-744): keep caption highlighted on silence

---

src/transcript-plugin.tsx
src/utils.ts

1. filter captions by language
2. in case if first filter returns more than 1 caption - make a filter by label
3. in case if second filter returns more than 1 caption - make a filter by index
4. in case if any filters doesn’t return anything - use first caption from caption list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/37)

chore(REACH2-743) - filter captions by lang, label and index

---

src/components/Caption/Caption.tsx
src/components/Caption/caption.scss

- added margin when time disabled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/39)

chore(REACH2-789): style fix when captions without time

---

src/components/Search/search.scss
src/components/Transcript/transcript.scss
src/components/caption-list/captionList.scss

- style changes according to design: https://zpl.io/anekd0Q
Facing egde-case between next sizes:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/41)

REACH2-790 - design changes for wide screens

---

src/components/Caption/caption.scss

- added MS flag to css for text-selection in IE11 and Edge

chore(REACH2-788): fix style for text selection in IE

---

src/components/Search/search.tsx

prevent unnecessary re-render of Search component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/47)

chore(REACH2-799) - prevent unnecessary re-render of Search component

---

src/components/Search/search.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/48)

chore(REACH2-806) - css styles of selected text for Search component

---

src/components/Search/search.scss
src/components/Search/search.tsx

Issue happened because host page has styles for <p> tag with stronger selector than TW styles.
As a temporary solution <p> tag changed to <div>
Final solution - using 'normalize.css' for resetting all external styles for TW.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/51)

chore(REACH2-816) - search component styles

---

src/components/Caption/Caption.tsx
src/components/Transcript/transcript.tsx
src/components/caption-list/CaptionList.tsx
src/components/download-print-menu/download-print-menu.tsx
src/utils.ts

- fixed issue with scroll to match when user clicks on search arrows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/46)

chore(REACH2-802) - autoscroll on search

---

src/components/caption-list/CaptionList.tsx

hotfix for 'get' method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/52)

chore(ui): fixed get method

---

README.md
src/transcript-plugin.tsx
src/utils.ts

- use player enums to define expand mode of plugin;
- add to README plugin configuration

fix(REACH2-1004): use player enums to define plugin expand mode

---

src/components/caption/caption.tsx
src/components/close-button/index.tsx
src/components/search/search.tsx
src/components/transcript/transcript.tsx

**the issue:**
when transcript panel is open, navigating inside it using tab is not working properly- it is possible to navigate inside the transcript panel only after elements outside the player have been touched.
**root cause:**
tab index of transcript's elements are set to 1. the browser first navigating throughout elements with tabindex=0.
**solution:**
change tabIndex to 0.
Solves [FEV-1531](https://kaltura.atlassian.net/browse/FEV-1531)

fix(FEV-1531): when transcript panel is open, navigating inside it using tab is not working properly

---

src/components/transcript/transcript.tsx
src/transcript-plugin.tsx
translates/langs.i18n.json

1. handle loading error;
2. internalisation;
3. init plugin on `TRACKS_CHANGED` event that dispatches for both external and non-external text tracks

fix(FEV-1597): handle non-external text tracks

---

.github/workflows/common_test.yml
package.json
src/components/autoscroll-button/autoscroll-button.tsx
src/components/caption/caption.tsx
src/components/close-button/index.tsx
src/components/plugin-button/plugin-button.tsx
src/components/search/search.tsx
src/components/transcript/transcript.tsx
src/transcript-plugin.tsx
yarn.lock

The transition animation is broken when the side panel is activated
solve [FEV-1623](https://kaltura.atlassian.net/browse/FEV-1623)
fix transition animation
import from @playkit-js/common only components that Navigation plugin uses
add test workflow to GH actions
dependent PR: https://github.com/kaltura/playkit-js-common/pull/10
[FEV-1623]: https://kaltura.atlassian.net/browse/FEV-1623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEV-1623): The transition animation is broken when the side panel is activated 

---

src/components/popover-menu/popover-menu.scss
src/components/popover-menu/popover-menu.tsx
src/components/transcript-menu/transcript-menu.tsx
src/components/transcript/transcript.scss
src/components/transcript/transcript.tsx

Fixes after version testing:
- Add margin between buttons
- Disable menu items while plugin is loading (e.g. on text track change)
- Add aria-label and tooltips
- Add tab and arrow navigation to menu items
- Close popover menu when using tab to navigate outside of it

fix(FEC-12957): Transcript Plugin - move download transcript inside the plugin menu and "release" the download button.

---

src/transcript-plugin.tsx

**the issue:**
transcript panel open automatically only on the first entry in the playlist
**the solution:**
keep the current state for the next video, change the state only when the user close the panel by clicking the buttons.
solves [SUP-37538](https://kaltura.atlassian.net/browse/SUP-37538)
[SUP-37538]: https://kaltura.atlassian.net/browse/SUP-37538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-37538): Auto Populate Transcripts for all videos in a Playlist

---

src/components/plugin-button/plugin-button.tsx

Adding "aria-hidden" to show/hide icon.
related to https://github.com/kaltura/playkit-js-ui/pull/788
solves [ADA-33](https://kaltura.atlassian.net/browse/ADA-33)
[ADA-33]: https://kaltura.atlassian.net/browse/ADA-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-33): [V7-Acc] SVG icons need to be hidden from screen reader

---

cypress/.gitignore
cypress/public/index.html
package.json
yarn.lock

Add support win os

---

cypress/e2e/transcript.cy.ts
src/components/caption-list/captionList.tsx
src/components/transcript/transcript.tsx

**issue:**
when search something and then click tab to the caption items, the tab goes to the current caption and not to the caption from the search result. 
**solution:**
when display caption, check the activeSearchIndex, if this caption is the current search, change the currentCaptionRef to this caption.

fix(ADA-16): Transcript search results inaccessible to screen reader

---

src/components/autoscroll-button/autoscroll-button.tsx

**issue:**
screen reader announce only "button" on autoScroll button
**solution:** 
move the aria-label from the wrapping element to the button element
solves [ADA-104](https://kaltura.atlassian.net/browse/ADA-104)
[ADA-104]: https://kaltura.atlassian.net/browse/ADA-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-104): Button in the transcript does not have a programmatic name

---

src/index.ts
src/transcript-plugin.tsx

**fix: Wrong and inconsistent order of plugins**
**fix: Plugins buttons sometimes display with the wrong icon**
**solves: [FEC-13517](https://kaltura.atlassian.net/browse/FEC-13517) [FEC-13517](https://kaltura.atlassian.net/browse/FEC-13517)**
[FEC-13517]: https://kaltura.atlassian.net/browse/FEC-13517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEC-13517]: https://kaltura.atlassian.net/browse/FEC-13517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/kaltura/playkit-js-ui-managers/pull/51
https://github.com/kaltura/playkit-js-share/pull/38
https://github.com/kaltura/playkit-js-moderation/pull/74
https://github.com/kaltura/playkit-js-playlist/pull/53 …

fix(FEC-13517): Wrong and inconsistent order of plugins

---

src/components/popover-menu/popover-menu.tsx

**Issue:**
More transcript option button doesn't announce  its state “expanded” or “collapsed”. 
**Fix:**
Add aria-expanded on the button.
Solves [ADA-103](https://kaltura.atlassian.net/browse/ADA-103)
[ADA-103]: https://kaltura.atlassian.net/browse/ADA-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-103): Transcript Options button doesn't announce “expanded” or “collapsed

---

src/components/transcript/transcript.tsx
src/events/events.ts
src/events/index.ts
src/index.ts
src/transcript-plugin.tsx

https://github.com/kaltura/playkit-js-kava/pull/156

fix(FEC-13719): [Transcript Plugins]: Add Events (used by kava analytics)

---

src/transcript-plugin.tsx

**the issue:**
when `preventSeek` is active, transcript should be able to receive new captions in chunks.
**solution:**
- when receiving new captions, create the proper `captionKey`
- pass `captionKey` to `addCaptionData` function
- in `addCaptionData` set the new captions in the map according to the `captionKey` param, and not according to the `activeCaptionKey`
- extract the making of `captionKey` to a function so it will be determined in one place
**related PR:** https://github.com/kaltura/playkit-js-kaltura-cuepoints/pull/66
Solves FEC-13775

fix(FEC-13775): transcript shows only current caption line

---

src/components/popover-menu/popover-menu.tsx

**Issue:**
When open the dropdown for 'More transcript option' the screen reader doesn't announce "expanded"
**Solution:**
Leave the focus on the 'More transcript option' button so screen reader will announce the state again (instead of moving the focus automatically to the first item) and handle the next tab press to move the focus to the first item in the dropdown .
Solves [ADA-767](https://kaltura.atlassian.net/browse/ADA-767)
[ADA-767]: https://kaltura.atlassian.net/browse/ADA-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-767): “Expanded” isn't announced when expanding 'More transcript option' toggle button.

---

src/transcript-plugin.tsx

**issue**:  
**issue**:  the `_deactiveItem()` (which in turn calls `this.dispatchEvent(TranscriptEvents.TRANSCRIPT_CLOSE`)) is called twice , **one**: on close icon click, **second**: as a callback from onDeactivate() parm of sidePanels() API 
**solution**:  remove the callback, which is redundant since the `_deactiveItem()` is called manualy every time...
https://github.com/kaltura/playkit-js-navigation/pull/360
https://github.com/kaltura/playkit-js-qna/pull/342
https://github.com/kaltura/playkit-js-ui-managers/pull/52

fix(FEC-13889): Download_close being reported too many times to application events

---

cypress/e2e/transcript.cy.ts
src/components/transcript/transcript.tsx

resolves: https://kaltura.atlassian.net/browse/FEC-13971

fix(FEC-13971): Disable detach feature on mobile devices

---

cypress/e2e/transcript.cy.ts
src/components/transcript-menu/transcript-menu.tsx
src/components/transcript/transcript.tsx

1. Use `ResizeObserver` to handle size of transcript plugin
2. Move detach button into transcript menu if plugin size <= 240px
Resolves: https://kaltura.atlassian.net/browse/FEC-13981

fix(FEC-13981): move detach in 3 dots menu

---

src/components/transcript/transcript.scss
src/components/transcript/transcript.tsx
src/transcript-plugin.tsx

1. fix focus styles inside detach window
2. disconnect resize handler on `componentWillUnmount`
3. fix issue with Safari, when caption language firstly `undefined` then `""` (empty string)
Resolves: https://kaltura.atlassian.net/browse/FEC-14004

fix(FEC-14004): add focus styles

---

cypress/e2e/transcript.cy.ts
src/components/caption/caption.tsx
translations/en.i18n.json

**Issue:**
Each line in the transcript is read as a button but there is no explanation why it's a button
**Fix:**
Adding additional explanation on in the aria-label
solves [ADA-597](https://kaltura.atlassian.net/browse/ADA-597)
[ADA-597]: https://kaltura.atlassian.net/browse/ADA-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-597): EBSCO (ADA) Transcript - each line is read as a button

---

src/components/caption-list/captionList.tsx
src/components/transcript/transcript.scss
src/components/transcript/transcript.tsx

**Issue:**
When user pick an instance of the search result, there is no quick mechanism to get to the line in the transcript with the word from the search box.
**Solution:**
Move the focus to the current line from the search result
Solves [ADA-1064](https://kaltura.atlassian.net/browse/ADA-1064)
[ADA-1064]: https://kaltura.atlassian.net/browse/ADA-1064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1064): Transcript search results inaccessible to screen reader followup from ADA-16

---

src/components/caption/caption.scss

**Issue:**
when you search in the text box, the strings that match to the search text have orange background and the text is white. it doesn't have good contrast
**Fix:**
change text color to black
solves [ADA-1689](https://kaltura.atlassian.net/browse/ADA-1689)
[ADA-1689]: https://kaltura.atlassian.net/browse/ADA-1689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1689): [Strategic Blue / University of Sheffield] - highlight search text within the video

---

src/components/search/search.tsx

Issue:
When focusing with tab on arrow buttons or x button (inside input filed), shift+tab will move the focus to plugin button instead of the previous element.
Fix:
Move the focus to plugin button only if the activeElement is the first element in the input filed.
Solves [FEC-14235](https://kaltura.atlassian.net/browse/FEC-14235)
[FEC-14235]: https://kaltura.atlassian.net/browse/FEC-14235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-14235): Player v7 | Transcript | Navigate order with Shift+tab from search result arrows is off.

---

src/components/search/search.tsx

Issue:
When the focus is in input filed before playing the video (with preload: auto), focus doesn't move to large play button with shift+tab
Fix: 
Adding the focus handling only after first play.
solves [FEC-14237](https://kaltura.atlassian.net/browse/FEC-14237)
[FEC-14237]: https://kaltura.atlassian.net/browse/FEC-14237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-14237): Player v7 | No option to Shift+tab backwards from transcript plugin to the play, previous & next buttons.

---

cypress/e2e/transcript.cy.ts
src/components/caption/caption.tsx
translations/en.i18n.json

Change the times in the caption aria-label to be read as a text with hours/minutes/seconds.
Using the duration-humanizer implementation was added here - https://github.com/kaltura/playkit-js-ui/pull/955 
Solves [ADA-1988](https://kaltura.atlassian.net/browse/ADA-1988)
[ADA-1988]: https://kaltura.atlassian.net/browse/ADA-1988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1988): Change time to be read as text

---

src/transcript-plugin.tsx

**Issue:**
When caption doesn't have label, it doesn't appear in the transcript panel.
**Root cause:** 
Caption data is saved with key of: {language}-{label} so where it no label it will be: language-undefined.
The compare is done between this string and the {language}-{label} coming from the engine, engine added name to caption when it's empty. so there is mismatch between the values.
**Fix:**
remove the label from the captionKay so comparing will be only between language.

fix(SUP-46361): Transcript visibility issue with VTT captions and Label usage in Kaltura Player v7.

---

package.json
yarn.lock

Issue:
previous and next search buttons receive focus even there is no result and it's disabled.
Fix:
update common version with fix: when the buttons are disabled, tabindex=-1
Solves [ADA-1961](https://kaltura.atlassian.net/browse/ADA-1961)
[ADA-1961]: https://kaltura.atlassian.net/browse/ADA-1961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1961): Disabled previous search and next search receive keyboard tab focus

---

src/components/caption/caption.tsx
src/components/transcript/transcript.tsx
src/events/events.ts
src/transcript-plugin.tsx

Issue: 
There is not scrolling when user enter search word, therefore search result is not visible to the user.
fix:
Handle scrolling to the caption ref result by using new event of scrolling.
solved [SUP-40290](https://kaltura.atlassian.net/browse/SUP-40290)
[SUP-40290]: https://kaltura.atlassian.net/browse/SUP-40290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-40290): Transcript Search Doesn't Show Results Right Away

---

src/components/transcript/transcript.scss

Issue:
Background color of "Go to result" button is Tone 5
Fix:
Background color of "Go to result" button has changed to Tone 6.
Solved  [ADA-1629]
(https://kaltura.atlassian.net/browse/ADA-1629)
[ADA-1629]: https://kaltura.atlassian.net/browse/ADA-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1629): Player v7 | Transcript | "Go to result" button background color doesn't match figma

---

src/components/caption/caption.tsx

Issue:
Typing in the search box causes player aligment issue.
Issue is caused due to the using of scrollIntoView function.
Fix:
Scroll with:
this.props.scrollTo(this._captionRef);
solved [FEC-14391](https://kaltura.atlassian.net/browse/FEC-14391)
[FEC-14391]: https://kaltura.atlassian.net/browse/FEC-14391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix (FEC-14391): Player v7 | Transcript | Typing in the search box causes player aligment issue.

---

src/components/search/search.tsx

This solves https://kaltura.atlassian.net/browse/ADA-2923 by focusing the Search input on opening/closing popout

fix(ADA-2923): Transcript popout focus management
