kaltura/playkit-js-transcript

- package-lock.json
- package.json
- src/plugin.tsx
- src/utils.ts
- VTT type support
- move srt parser from external library to utils
> Reach2 680 captions type support

- src/components/Transcript/transcript.scss
- src/components/spinner/spinner.scss
- src/plugin.tsx
- test/index.template.ejs
- updated initial logic (according to contrib changes)
- configurable opening by default
- fixed styles
- load fonts with contrib-fontManager
> Reach2 671 open close by default

- src/components/Caption/Caption.tsx
- src/components/Caption/caption.scss
- src/components/caption-list/CaptionList.tsx
- src/utils.ts
> Fev 452 times column styles

- src/components/Transcript/transcript.tsx
Autoscroll starts automatically and the search UI cleared on transcript language changes.
> chore(FEV-450): reset TW features on language changes

- src/components/Caption/caption.scss
- src/variables.scss
1. changed captions line-height;
2. changed captions font-size;
3. changed captions search match background color;
> (fev 461,fev 462,fev 456) tw styles

- src/transcript-plugin.scss
- src/transcript-plugin.tsx
made hover\selected styles for TW icon
> chore(FEV-455): add hover styles

- src/components/Search/search.scss
- src/components/Search/search.tsx
- src/components/Transcript/transcript.scss
1) changed search-input height to 32px;
2) changed search-input colors according to design;
3) changed margins according to design;
> (fev 464,fev 459) search bar styles

- src/components/Search/search.scss
- src/components/download-print-menu/download-print-menu.scss
fixed transparent styles for Edge browser
> chore(REACH2-746): fix transparent styles for edge browser

- src/components/Caption/Caption.tsx
- src/components/Caption/caption.scss
- src/components/Search/search.scss
- src/components/Transcript/transcript.scss
- src/components/caption-list/CaptionList.tsx
- src/transcript-plugin.tsx
- fix for time column
- fix for caption fetching
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/36)
> chore: fix for time column, fix for caption fetch

- src/transcript-plugin.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/40)
> REACH2-783 - fix KS bug

- src/components/Search/search.scss
- src/components/Transcript/transcript.scss
- src/components/Transcript/transcript.tsx
- src/components/caption-list/captionList.scss
- src/transcript-plugin.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/43)
> Reach2 790 design changes(caption centering)

- src/components/Transcript/transcript.tsx
- src/transcript-plugin.tsx
- autoscroll works between 33% and 66% of TW height.
- removed debounce on scroll
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/44)
> chore(REACH2-742) - new logic of autoscroll

- test/index.ejs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/49)
> chore(REACH2-797) - dev-server: IE11 support

- src/transcript-plugin.tsx
- src/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-transcript/50)
> Reach2 782 use ubject utils from contrib

- src/components/download-print-menu/download-print-menu.tsx
- src/transcript-plugin.tsx
- translates/langs.i18n.json
1) change label content;
2) add i18n
> fix(FEV-1356): transcript print/download labels

- src/components/spinner/spinner.scss
- src/components/spinner/spinner.tsx
- src/transcript-plugin.tsx
1) handle loading animation;
2) fix a11y;
3) prevent icons duplication on media switch;
4) fix styles for loading icon;
> fix(FEV-1355): Transcript only works for first language in videos that contain multiple captions

- src/transcript-plugin.tsx
init transcript plugin only if captions exist
> fix(FEV-1534): If Kaltura BE does not have captions the Transcript plugin should not be displayed

- cypress/e2e/transcript.cy.ts
- package.json
- src/components/autoscroll-button/autoscroll-button.tsx
- src/components/caption/caption.tsx
- src/components/plugin-button/plugin-button.tsx
- src/components/transcript/transcript.tsx
- src/transcript-plugin.tsx
- yarn.lock
1. handle focus change on plugin close;
2. upd tests
> fix(FEC-12918): When users close a menu by clicking the close button, focus should go back to the button that opened the plugin

- src/components/transcript/transcript.scss
> fix(FEC-12951): Transcript plugin side panel  background is transparent

- package.json
add the translation for the files array in package json 
Solves FEV-1658
> feat(FEV-1658): Add translation for Spanish on transcript plugin

- src/components/transcript/transcript.scss
> fix(FEC-13050): CSS backdrop-filter property is not supposed in Safari

- src/components/caption-list/captionList.tsx
issue:
remove ARIA live property for transcript
> fix(ADA-44): [V7-Acc] Remove Aria Live property where not required

- package.json
- src/transcript-plugin.tsx
- src/utils/utils.ts
- yarn.lock
solves: https://kaltura.atlassian.net/browse/FEC-13437
1) add types for sanitize-html lib
2) sanitize captions before print and download
3) handle <> char codes
> fix(FEC-13437): Transcript doesn't handle html tags as expected.

- cypress/e2e/transcript.cy.ts
- package.json
> chore: upd tests

- cypress/e2e/transcript.cy.ts
- src/components/plugin-button/plugin-button.tsx
**issue:**
When embed player in a form element and click on the plugin button, the page refreshes.
**solution:**
add type=button on the plugin button
solves [SUP-39294](https://kaltura.atlassian.net/browse/SUP-39294)
[SUP-39294]: https://kaltura.atlassian.net/browse/SUP-39294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-39294): Page refreshes after clicking on player buttons

- translations/es.i18n.json
adding Spanish translation 
solves  [SUP-40127](https://kaltura.atlassian.net/browse/SUP-40127)
[SUP-40127]: https://kaltura.atlassian.net/browse/SUP-40127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-40127): Correcting and adding spanish translation

- translations/es.i18n.json
solves [SUP-40351](https://kaltura.atlassian.net/browse/SUP-40351)
[SUP-40351]: https://kaltura.atlassian.net/browse/SUP-40351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-40351): [eLearning] correcting typo in Spanish translation

- .github/workflows/run_tests.yaml
- src/components/transcript/transcript.tsx
- src/events/index.ts
- src/index.ts
- src/transcript-plugin.tsx
> fix(SUP-0): fix import issue

- .github/workflows/run_tests.yaml
- src/components/transcript/transcript.tsx
debouncing search event to be sent on  minimum  of 2 sec timeframe
> fix(FEC-13784): Search event is sent too often - need to be debounced for minimum 2 sec

- demo/index.html
- demo/style.css
- src/components/caption/caption.tsx
- src/transcript-plugin.tsx
- webpack.config.js
> fix(FEC-13896): Transcript highlight current line doesn't show after changing caption language.

- src/components/attach-placeholder/attach-placeholder.scss
- src/components/transcript/transcript.scss
- src/components/transcript/transcript.tsx
- src/variables.scss
Detach style fixes
resolves: https://kaltura.atlassian.net/browse/FEC-13951
resolves: https://kaltura.atlassian.net/browse/FEC-13952
resolves: https://kaltura.atlassian.net/browse/FEC-13980
> fix(FEC-13951): detach issues (FEC-13952, FEC-13980)

- src/components/attach-placeholder/attach-placeholder.scss
- src/components/attach-placeholder/attach-placeholder.tsx
- src/transcript-plugin.tsx
- translations/en.i18n.json
resolves: https://kaltura.atlassian.net/browse/FEC-13950
> fix(FEC-13950): align attach placeholder with design

- package.json
- src/events/events.ts
- src/transcript-plugin.tsx
- yarn.lock
Add detach analytic events
solves: https://kaltura.atlassian.net/browse/FEC-13749
> feat(FEC-13749): Detach analytic events

- src/components/transcript/transcript.tsx
- src/transcript-plugin.tsx
Resolves: https://kaltura.atlassian.net/browse/FEC-13729
> feat(FEC-13729): audio-player support

- src/components/transcript/transcript.tsx
- translations/en.i18n.json
Resolves https://kaltura.atlassian.net/browse/FEC-13994
> fix(FEC-13994): change button label

- package.json
- src/components/popover-menu/popover-menu.tsx
- src/components/transcript-menu/transcript-menu.tsx
- src/components/transcript/transcript.tsx
- yarn.lock
resolves: https://kaltura.atlassian.net/browse/FEC-14023
> fix(FEC-14023): tooltip fix for detach mode

- src/transcript-plugin.tsx
Add null checks for AudioPluginsManager
Resolves [FEC-14063](https://kaltura.atlassian.net/browse/FEC-14063)
[FEC-14063]: https://kaltura.atlassian.net/browse/FEC-14063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-14063): "Remove" errors in console for Download & transcript (transcript also failed to load)

- src/components/caption-list/captionList.tsx
- src/components/transcript/transcript.scss
Reverts kaltura/playkit-js-transcript#211
> Revert "fix(ADA-1064): Transcript search results inaccessible to screen reader followup from ADA-16"

- cypress/e2e/transcript.cy.ts
- package.json
- src/components/caption-list/captionList.tsx
- src/components/caption/caption.tsx
- src/components/transcript/transcript.scss
- src/components/transcript/transcript.tsx
- src/events/events.ts
- src/transcript-plugin.tsx
- translations/en.i18n.json
- yarn.lock
1. announce current search match
2. add "Go to result" button that allows jump to current search match
solves https://kaltura.atlassian.net/browse/ADA-1064
> fix(ADA-1064) search result announcements

- cypress/e2e/transcript.cy.ts
- src/components/small-screen-slate/small-screen-slate.scss
- src/components/transcript/transcript.tsx
Resolves: https://kaltura.atlassian.net/browse/FEC-14137
> fix(FEC-14137) show slate only on tiny player size

- cypress/e2e/transcript.cy.ts
- package.json
- src/components/popover-menu/popover-menu-item.tsx
- src/components/popover-menu/popover-menu.scss
- src/components/popover-menu/popover-menu.tsx
- src/components/transcript-menu/transcript-menu.tsx
- src/components/transcript/transcript.tsx
- src/transcript-plugin.tsx
- src/utils/utils.ts
- yarn.lock
> fix(FEC-14118): change transcript language in transcript plugin

- src/components/popover-menu/popover-menu.scss
- src/components/transcript-menu/transcript-menu.tsx
resolves https://kaltura.atlassian.net/browse/FEC-14243
resolves https://kaltura.atlassian.net/browse/FEC-14242
> fix(FEC-14244): fix label and max with of sub-ment

- src/components/transcript/transcript.tsx
This solves https://kaltura.atlassian.net/browse/ADA-2443
I've added Ctrl+j shortcut to "Go to result" button
> fix(ADA-2443): Add shortcut to Go to result button

- src/components/search/search.tsx
resolves: https://kaltura.atlassian.net/browse/FEC-14452
> fix(FEC-14452): move focus back to plugin button fix

- src/transcript-plugin.tsx
This completes this https://kaltura.atlassian.net/browse/ADA-2313 by translating the Transcript string
> fix(ADA-2313): Add translation to ariaLabel
